// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'ai/settings.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'vpl/dto.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1782856766;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_ikarus',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<AiSettings> crateAiSettingsAiSettingsCurrent();

  Future<AiSettings> crateAiSettingsAiSettingsEmpty();

  Future<void> crateAiSettingsAiSettingsUpdate({required AiSettings that});

  Future<void> crateInitApp();

  Future<void> crateLaunch();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<AiSettings> crateAiSettingsAiSettingsCurrent() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ai_settings,
          decodeErrorData: null,
        ),
        constMeta: kCrateAiSettingsAiSettingsCurrentConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateAiSettingsAiSettingsCurrentConstMeta =>
      const TaskConstMeta(debugName: "ai_settings_current", argNames: []);

  @override
  Future<AiSettings> crateAiSettingsAiSettingsEmpty() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ai_settings,
          decodeErrorData: null,
        ),
        constMeta: kCrateAiSettingsAiSettingsEmptyConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateAiSettingsAiSettingsEmptyConstMeta =>
      const TaskConstMeta(debugName: "ai_settings_empty", argNames: []);

  @override
  Future<void> crateAiSettingsAiSettingsUpdate({required AiSettings that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_ai_settings(that, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateAiSettingsAiSettingsUpdateConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateAiSettingsAiSettingsUpdateConstMeta =>
      const TaskConstMeta(debugName: "ai_settings_update", argNames: ["that"]);

  @override
  Future<void> crateInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateLaunch() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateLaunchConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateLaunchConstMeta =>
      const TaskConstMeta(debugName: "launch", argNames: []);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AiSettings dco_decode_ai_settings(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return AiSettings(
      textUrl: dco_decode_String(arr[0]),
      textKey: dco_decode_String(arr[1]),
      textModel: dco_decode_String(arr[2]),
      embedUrl: dco_decode_String(arr[3]),
      embedKey: dco_decode_String(arr[4]),
      embedModel: dco_decode_String(arr[5]),
      embedDimensions: dco_decode_i_32(arr[6]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  AiSettings dco_decode_box_autoadd_ai_settings(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_ai_settings(raw);
  }

  @protected
  DtoValue dco_decode_box_autoadd_dto_value(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_dto_value(raw);
  }

  @protected
  DtoVariable dco_decode_box_autoadd_dto_variable(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_dto_variable(raw);
  }

  @protected
  DtoCondition dco_decode_dto_condition(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return DtoCondition.values[raw as int];
  }

  @protected
  DtoScope dco_decode_dto_scope(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return DtoScope(field0: dco_decode_list_dto_statement(arr[0]));
  }

  @protected
  DtoStatement dco_decode_dto_statement(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return DtoStatement_Assignment(
          identifier: dco_decode_String(raw[1]),
          value: dco_decode_box_autoadd_dto_value(raw[2]),
        );
      case 1:
        return DtoStatement_If(
          left: dco_decode_box_autoadd_dto_variable(raw[1]),
          right: dco_decode_box_autoadd_dto_variable(raw[2]),
          condition: dco_decode_dto_condition(raw[3]),
        );
      case 2:
        return DtoStatement_For(
          left: dco_decode_box_autoadd_dto_variable(raw[1]),
          right: dco_decode_box_autoadd_dto_variable(raw[2]),
          condition: dco_decode_dto_condition(raw[3]),
        );
      case 3:
        return DtoStatement_End();
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  DtoValue dco_decode_dto_value(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return DtoValue_Undefined();
      case 1:
        return DtoValue_Number(dco_decode_f_64(raw[1]));
      case 2:
        return DtoValue_String(dco_decode_String(raw[1]));
      case 3:
        return DtoValue_Boolean(dco_decode_bool(raw[1]));
      case 4:
        return DtoValue_Element();
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  DtoVariable dco_decode_dto_variable(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return DtoVariable_Identifier(dco_decode_String(raw[1]));
      case 1:
        return DtoVariable_Value(dco_decode_box_autoadd_dto_value(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<DtoStatement> dco_decode_list_dto_statement(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_dto_statement).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AiSettings sse_decode_ai_settings(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_textUrl = sse_decode_String(deserializer);
    var var_textKey = sse_decode_String(deserializer);
    var var_textModel = sse_decode_String(deserializer);
    var var_embedUrl = sse_decode_String(deserializer);
    var var_embedKey = sse_decode_String(deserializer);
    var var_embedModel = sse_decode_String(deserializer);
    var var_embedDimensions = sse_decode_i_32(deserializer);
    return AiSettings(
      textUrl: var_textUrl,
      textKey: var_textKey,
      textModel: var_textModel,
      embedUrl: var_embedUrl,
      embedKey: var_embedKey,
      embedModel: var_embedModel,
      embedDimensions: var_embedDimensions,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  AiSettings sse_decode_box_autoadd_ai_settings(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_ai_settings(deserializer));
  }

  @protected
  DtoValue sse_decode_box_autoadd_dto_value(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_dto_value(deserializer));
  }

  @protected
  DtoVariable sse_decode_box_autoadd_dto_variable(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_dto_variable(deserializer));
  }

  @protected
  DtoCondition sse_decode_dto_condition(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return DtoCondition.values[inner];
  }

  @protected
  DtoScope sse_decode_dto_scope(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_list_dto_statement(deserializer);
    return DtoScope(field0: var_field0);
  }

  @protected
  DtoStatement sse_decode_dto_statement(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_identifier = sse_decode_String(deserializer);
        var var_value = sse_decode_box_autoadd_dto_value(deserializer);
        return DtoStatement_Assignment(
          identifier: var_identifier,
          value: var_value,
        );
      case 1:
        var var_left = sse_decode_box_autoadd_dto_variable(deserializer);
        var var_right = sse_decode_box_autoadd_dto_variable(deserializer);
        var var_condition = sse_decode_dto_condition(deserializer);
        return DtoStatement_If(
          left: var_left,
          right: var_right,
          condition: var_condition,
        );
      case 2:
        var var_left = sse_decode_box_autoadd_dto_variable(deserializer);
        var var_right = sse_decode_box_autoadd_dto_variable(deserializer);
        var var_condition = sse_decode_dto_condition(deserializer);
        return DtoStatement_For(
          left: var_left,
          right: var_right,
          condition: var_condition,
        );
      case 3:
        return DtoStatement_End();
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  DtoValue sse_decode_dto_value(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return DtoValue_Undefined();
      case 1:
        var var_field0 = sse_decode_f_64(deserializer);
        return DtoValue_Number(var_field0);
      case 2:
        var var_field0 = sse_decode_String(deserializer);
        return DtoValue_String(var_field0);
      case 3:
        var var_field0 = sse_decode_bool(deserializer);
        return DtoValue_Boolean(var_field0);
      case 4:
        return DtoValue_Element();
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  DtoVariable sse_decode_dto_variable(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_String(deserializer);
        return DtoVariable_Identifier(var_field0);
      case 1:
        var var_field0 = sse_decode_box_autoadd_dto_value(deserializer);
        return DtoVariable_Value(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<DtoStatement> sse_decode_list_dto_statement(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DtoStatement>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_dto_statement(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_ai_settings(AiSettings self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.textUrl, serializer);
    sse_encode_String(self.textKey, serializer);
    sse_encode_String(self.textModel, serializer);
    sse_encode_String(self.embedUrl, serializer);
    sse_encode_String(self.embedKey, serializer);
    sse_encode_String(self.embedModel, serializer);
    sse_encode_i_32(self.embedDimensions, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_ai_settings(
    AiSettings self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ai_settings(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_dto_value(
    DtoValue self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_dto_value(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_dto_variable(
    DtoVariable self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_dto_variable(self, serializer);
  }

  @protected
  void sse_encode_dto_condition(DtoCondition self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_dto_scope(DtoScope self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_dto_statement(self.field0, serializer);
  }

  @protected
  void sse_encode_dto_statement(DtoStatement self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case DtoStatement_Assignment(
        identifier: final identifier,
        value: final value,
      ):
        sse_encode_i_32(0, serializer);
        sse_encode_String(identifier, serializer);
        sse_encode_box_autoadd_dto_value(value, serializer);
      case DtoStatement_If(
        left: final left,
        right: final right,
        condition: final condition,
      ):
        sse_encode_i_32(1, serializer);
        sse_encode_box_autoadd_dto_variable(left, serializer);
        sse_encode_box_autoadd_dto_variable(right, serializer);
        sse_encode_dto_condition(condition, serializer);
      case DtoStatement_For(
        left: final left,
        right: final right,
        condition: final condition,
      ):
        sse_encode_i_32(2, serializer);
        sse_encode_box_autoadd_dto_variable(left, serializer);
        sse_encode_box_autoadd_dto_variable(right, serializer);
        sse_encode_dto_condition(condition, serializer);
      case DtoStatement_End():
        sse_encode_i_32(3, serializer);
    }
  }

  @protected
  void sse_encode_dto_value(DtoValue self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case DtoValue_Undefined():
        sse_encode_i_32(0, serializer);
      case DtoValue_Number(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_f_64(field0, serializer);
      case DtoValue_String(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_String(field0, serializer);
      case DtoValue_Boolean(field0: final field0):
        sse_encode_i_32(3, serializer);
        sse_encode_bool(field0, serializer);
      case DtoValue_Element():
        sse_encode_i_32(4, serializer);
    }
  }

  @protected
  void sse_encode_dto_variable(DtoVariable self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case DtoVariable_Identifier(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_String(field0, serializer);
      case DtoVariable_Value(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_box_autoadd_dto_value(field0, serializer);
    }
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_dto_statement(
    List<DtoStatement> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_dto_statement(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
