// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BrowserSingletonInner`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `lock`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `browser`, `is_running`, `pid`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BrowserSingleton>>
abstract class BrowserSingleton implements RustOpaqueInterface {
  static BrowserSingleton instance() => RustLib.instance.api
      .crateBrowserSingletonBrowserSingletonFrbOverrideInstance();

  Future<void> initialize();

  Future<bool> isRunning();

  Future<int?> pid();

  Future<void> registerListener({required FutureOr<void> Function() callback});
}
