// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `prepare`

Future<String?> open({required List<FileDialogFilter> filters}) =>
    RustLib.instance.api.crateSharedFileDialogOpen(filters: filters);

Future<String?> save({required List<FileDialogFilter> filters}) =>
    RustLib.instance.api.crateSharedFileDialogSave(filters: filters);

class FileDialogFilter {
  final String name;
  final List<String> extensions;

  const FileDialogFilter({required this.name, required this.extensions});

  @override
  int get hashCode => name.hashCode ^ extensions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileDialogFilter &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          extensions == other.extensions;
}
