// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `instance`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `eq`

class Settings {
  final String textGenerationUrl;
  final String textGenerationKey;
  final String textGenerationModel;

  const Settings({
    required this.textGenerationUrl,
    required this.textGenerationKey,
    required this.textGenerationModel,
  });

  static Future<Settings> current() =>
      RustLib.instance.api.crateSharedSettingsSettingsCurrent();

  Future<void> save() =>
      RustLib.instance.api.crateSharedSettingsSettingsSave(that: this);

  @override
  int get hashCode =>
      textGenerationUrl.hashCode ^
      textGenerationKey.hashCode ^
      textGenerationModel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Settings &&
          runtimeType == other.runtimeType &&
          textGenerationUrl == other.textGenerationUrl &&
          textGenerationKey == other.textGenerationKey &&
          textGenerationModel == other.textGenerationModel;
}
