// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../tokens.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they have generic arguments: `invoke`, `invoke`, `invoke`, `invoke`, `invoke`, `invoke`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Csv`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

Future<Val> symbol() => RustLib.instance.api.crateVplFunctionsCsvSymbol();

class FnCallCsvGet {
  final Val csv;
  final Val result;
  final Val row;
  final Val col;

  const FnCallCsvGet({
    required this.csv,
    required this.result,
    required this.row,
    required this.col,
  });

  static Future<FnCallCsvGet> default_() =>
      RustLib.instance.api.crateVplFunctionsCsvFnCallCsvGetDefault();

  @override
  int get hashCode =>
      csv.hashCode ^ result.hashCode ^ row.hashCode ^ col.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FnCallCsvGet &&
          runtimeType == other.runtimeType &&
          csv == other.csv &&
          result == other.result &&
          row == other.row &&
          col == other.col;
}

class FnCallCsvLoad {
  final Val csv;
  final Val file;

  const FnCallCsvLoad({required this.csv, required this.file});

  static Future<FnCallCsvLoad> default_() =>
      RustLib.instance.api.crateVplFunctionsCsvFnCallCsvLoadDefault();

  @override
  int get hashCode => csv.hashCode ^ file.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FnCallCsvLoad &&
          runtimeType == other.runtimeType &&
          csv == other.csv &&
          file == other.file;
}

class FnCallCsvNew {
  final Val csv;

  const FnCallCsvNew({required this.csv});

  static Future<FnCallCsvNew> default_() =>
      RustLib.instance.api.crateVplFunctionsCsvFnCallCsvNewDefault();

  @override
  int get hashCode => csv.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FnCallCsvNew &&
          runtimeType == other.runtimeType &&
          csv == other.csv;
}

class FnCallCsvRowCount {
  final Val csv;
  final Val result;

  const FnCallCsvRowCount({required this.csv, required this.result});

  static Future<FnCallCsvRowCount> default_() =>
      RustLib.instance.api.crateVplFunctionsCsvFnCallCsvRowCountDefault();

  @override
  int get hashCode => csv.hashCode ^ result.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FnCallCsvRowCount &&
          runtimeType == other.runtimeType &&
          csv == other.csv &&
          result == other.result;
}

class FnCallCsvSave {
  final Val csv;
  final Val file;

  const FnCallCsvSave({required this.csv, required this.file});

  static Future<FnCallCsvSave> default_() =>
      RustLib.instance.api.crateVplFunctionsCsvFnCallCsvSaveDefault();

  @override
  int get hashCode => csv.hashCode ^ file.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FnCallCsvSave &&
          runtimeType == other.runtimeType &&
          csv == other.csv &&
          file == other.file;
}

class FnCallCsvSet {
  final Val csv;
  final Val row;
  final Val col;
  final Val value;

  const FnCallCsvSet({
    required this.csv,
    required this.row,
    required this.col,
    required this.value,
  });

  static Future<FnCallCsvSet> default_() =>
      RustLib.instance.api.crateVplFunctionsCsvFnCallCsvSetDefault();

  @override
  int get hashCode =>
      csv.hashCode ^ row.hashCode ^ col.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FnCallCsvSet &&
          runtimeType == other.runtimeType &&
          csv == other.csv &&
          row == other.row &&
          col == other.col &&
          value == other.value;
}
