// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../tokens.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they have generic arguments: `invoke`, `invoke`, `invoke`, `invoke`, `invoke`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`

Future<Val> symbol() => RustLib.instance.api.crateVplFunctionsElementSymbol();

class FnCallElementClick {
  final Val element;

  const FnCallElementClick({required this.element});

  static Future<FnCallElementClick> default_() =>
      RustLib.instance.api.crateVplFunctionsElementFnCallElementClickDefault();

  @override
  int get hashCode => element.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FnCallElementClick &&
          runtimeType == other.runtimeType &&
          element == other.element;
}

class FnCallElementGetInnerHtml {
  final Val element;
  final Val result;

  const FnCallElementGetInnerHtml({
    required this.element,
    required this.result,
  });

  static Future<FnCallElementGetInnerHtml> default_() => RustLib.instance.api
      .crateVplFunctionsElementFnCallElementGetInnerHtmlDefault();

  @override
  int get hashCode => element.hashCode ^ result.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FnCallElementGetInnerHtml &&
          runtimeType == other.runtimeType &&
          element == other.element &&
          result == other.result;
}

class FnCallElementGetOuterHtml {
  final Val element;
  final Val result;

  const FnCallElementGetOuterHtml({
    required this.element,
    required this.result,
  });

  static Future<FnCallElementGetOuterHtml> default_() => RustLib.instance.api
      .crateVplFunctionsElementFnCallElementGetOuterHtmlDefault();

  @override
  int get hashCode => element.hashCode ^ result.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FnCallElementGetOuterHtml &&
          runtimeType == other.runtimeType &&
          element == other.element &&
          result == other.result;
}

class FnCallElementGetText {
  final Val element;
  final Val result;

  const FnCallElementGetText({required this.element, required this.result});

  static Future<FnCallElementGetText> default_() => RustLib.instance.api
      .crateVplFunctionsElementFnCallElementGetTextDefault();

  @override
  int get hashCode => element.hashCode ^ result.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FnCallElementGetText &&
          runtimeType == other.runtimeType &&
          element == other.element &&
          result == other.result;
}

class FnCallElementType {
  final Val element;
  final Val text;

  const FnCallElementType({required this.element, required this.text});

  static Future<FnCallElementType> default_() =>
      RustLib.instance.api.crateVplFunctionsElementFnCallElementTypeDefault();

  @override
  int get hashCode => element.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FnCallElementType &&
          runtimeType == other.runtimeType &&
          element == other.element &&
          text == other.text;
}
