// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../tokens.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they have generic arguments: `invoke`, `invoke`, `invoke`, `invoke`, `invoke`, `invoke`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`

Future<Val> symbol() => RustLib.instance.api.crateVplFunctionsPageSymbol();

class FnCallPageClose {
  final Val page;
  final Val url;

  const FnCallPageClose({required this.page, required this.url});

  static Future<FnCallPageClose> default_() =>
      RustLib.instance.api.crateVplFunctionsPageFnCallPageCloseDefault();

  @override
  int get hashCode => page.hashCode ^ url.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FnCallPageClose &&
          runtimeType == other.runtimeType &&
          page == other.page &&
          url == other.url;
}

class FnCallPageFindElement {
  final Val page;
  final Val element;
  final Val selector;

  const FnCallPageFindElement({
    required this.page,
    required this.element,
    required this.selector,
  });

  static Future<FnCallPageFindElement> default_() =>
      RustLib.instance.api.crateVplFunctionsPageFnCallPageFindElementDefault();

  @override
  int get hashCode => page.hashCode ^ element.hashCode ^ selector.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FnCallPageFindElement &&
          runtimeType == other.runtimeType &&
          page == other.page &&
          element == other.element &&
          selector == other.selector;
}

class FnCallPageGetByIndex {
  final Val page;
  final Val index;

  const FnCallPageGetByIndex({required this.page, required this.index});

  static Future<FnCallPageGetByIndex> default_() =>
      RustLib.instance.api.crateVplFunctionsPageFnCallPageGetByIndexDefault();

  @override
  int get hashCode => page.hashCode ^ index.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FnCallPageGetByIndex &&
          runtimeType == other.runtimeType &&
          page == other.page &&
          index == other.index;
}

class FnCallPageGetCount {
  final Val result;

  const FnCallPageGetCount({required this.result});

  static Future<FnCallPageGetCount> default_() =>
      RustLib.instance.api.crateVplFunctionsPageFnCallPageGetCountDefault();

  @override
  int get hashCode => result.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FnCallPageGetCount &&
          runtimeType == other.runtimeType &&
          result == other.result;
}

class FnCallPageNew {
  final Val page;
  final Val url;

  const FnCallPageNew({required this.page, required this.url});

  static Future<FnCallPageNew> default_() =>
      RustLib.instance.api.crateVplFunctionsPageFnCallPageNewDefault();

  @override
  int get hashCode => page.hashCode ^ url.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FnCallPageNew &&
          runtimeType == other.runtimeType &&
          page == other.page &&
          url == other.url;
}

class FnCallPageWaitForNavigation {
  final Val page;
  final Val url;

  const FnCallPageWaitForNavigation({required this.page, required this.url});

  static Future<FnCallPageWaitForNavigation> default_() => RustLib.instance.api
      .crateVplFunctionsPageFnCallPageWaitForNavigationDefault();

  @override
  int get hashCode => page.hashCode ^ url.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FnCallPageWaitForNavigation &&
          runtimeType == other.runtimeType &&
          page == other.page &&
          url == other.url;
}
