// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../tokens.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they have generic arguments: `invoke`, `invoke`, `invoke`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`

class FnCallSystemPrint {
  final Val content;

  const FnCallSystemPrint({required this.content});

  static Future<FnCallSystemPrint> default_() =>
      RustLib.instance.api.crateVplFunctionsSystemFnCallSystemPrintDefault();

  @override
  int get hashCode => content.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FnCallSystemPrint &&
          runtimeType == other.runtimeType &&
          content == other.content;
}

class FnCallSystemSleep {
  final Val ms;

  const FnCallSystemSleep({required this.ms});

  static Future<FnCallSystemSleep> default_() =>
      RustLib.instance.api.crateVplFunctionsSystemFnCallSystemSleepDefault();

  @override
  int get hashCode => ms.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FnCallSystemSleep &&
          runtimeType == other.runtimeType &&
          ms == other.ms;
}

class FnCallSystemStop {
  const FnCallSystemStop();

  static Future<FnCallSystemStop> default_() =>
      RustLib.instance.api.crateVplFunctionsSystemFnCallSystemStopDefault();

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FnCallSystemStop && runtimeType == other.runtimeType;
}
