// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'ast.freezed.dart';

@freezed
sealed class Assignment with _$Assignment {
  const Assignment._();

  const factory Assignment.declare({
    required String name,
    required Value value,
  }) = Assignment_Declare;
}

@freezed
sealed class Value with _$Value {
  const Value._();

  const factory Value.number(double field0) = Value_Number;
  const factory Value.string(String field0) = Value_String;
  const factory Value.boolean(bool field0) = Value_Boolean;
}
