// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'functions.dart';
import 'functions/csv.dart';
import 'functions/element.dart';
import 'functions/page.dart';
import 'functions/system.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'raw_tokens.dart';
import 'tokens.dart';

// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `current`, `update`

class RawScopeBinding {
  const RawScopeBinding();

  static Future<void> registerGetter({
    required FutureOr<RawScope> Function() cb,
  }) =>
      RustLib.instance.api.crateVplBindingRawScopeBindingRegisterGetter(cb: cb);

  static Future<void> registerSetter({
    required FutureOr<void> Function(RawScope) cb,
  }) =>
      RustLib.instance.api.crateVplBindingRawScopeBindingRegisterSetter(cb: cb);

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RawScopeBinding && runtimeType == other.runtimeType;
}
