// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'dto.freezed.dart';

enum DtoCondition {
  not,
  equal,
  lessThan,
  lessThenOrEqual,
  greaterThen,
  greaterThenOrEqual,
}

class DtoScope {
  final List<DtoStatement> field0;

  const DtoScope({required this.field0});

  @override
  int get hashCode => field0.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DtoScope &&
          runtimeType == other.runtimeType &&
          field0 == other.field0;
}

@freezed
sealed class DtoStatement with _$DtoStatement {
  const DtoStatement._();

  const factory DtoStatement.assignment({
    required String identifier,
    required DtoValue value,
  }) = DtoStatement_Assignment;
  const factory DtoStatement.if_({
    required DtoVariable left,
    required DtoVariable right,
    required DtoCondition condition,
  }) = DtoStatement_If;
  const factory DtoStatement.for_({
    required DtoVariable left,
    required DtoVariable right,
    required DtoCondition condition,
  }) = DtoStatement_For;
  const factory DtoStatement.end() = DtoStatement_End;
}

@freezed
sealed class DtoValue with _$DtoValue {
  const DtoValue._();

  const factory DtoValue.undefined() = DtoValue_Undefined;
  const factory DtoValue.number(double field0) = DtoValue_Number;
  const factory DtoValue.string(String field0) = DtoValue_String;
  const factory DtoValue.boolean(bool field0) = DtoValue_Boolean;
  const factory DtoValue.element() = DtoValue_Element;
}

@freezed
sealed class DtoVariable with _$DtoVariable {
  const DtoVariable._();

  const factory DtoVariable.identifier(String field0) = DtoVariable_Identifier;
  const factory DtoVariable.value(DtoValue field0) = DtoVariable_Value;
}
