// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'functions/csv.dart';
import 'functions/element.dart';
import 'functions/page.dart';
import 'functions/system.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'tokens.dart';
part 'functions.freezed.dart';

// These functions are ignored because they have generic arguments: `invoke`, `invoke`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`

@freezed
sealed class FnCall with _$FnCall {
  const FnCall._();

  const factory FnCall.systemStop(FnCallSystemStop field0) = FnCall_SystemStop;
  const factory FnCall.systemPrint(FnCallSystemPrint field0) =
      FnCall_SystemPrint;
  const factory FnCall.systemSleep(FnCallSystemSleep field0) =
      FnCall_SystemSleep;
  const factory FnCall.pageNew(FnCallPageNew field0) = FnCall_PageNew;
  const factory FnCall.pageGetByIndex(FnCallPageGetByIndex field0) =
      FnCall_PageGetByIndex;
  const factory FnCall.pageGetCount(FnCallPageGetCount field0) =
      FnCall_PageGetCount;
  const factory FnCall.pageWaitForNavigation(
    FnCallPageWaitForNavigation field0,
  ) = FnCall_PageWaitForNavigation;
  const factory FnCall.pageClose(FnCallPageClose field0) = FnCall_PageClose;
  const factory FnCall.pageFindElement(FnCallPageFindElement field0) =
      FnCall_PageFindElement;
  const factory FnCall.elementGetOuterHtml(FnCallElementGetOuterHtml field0) =
      FnCall_ElementGetOuterHtml;
  const factory FnCall.elementGetInnerHtml(FnCallElementGetInnerHtml field0) =
      FnCall_ElementGetInnerHtml;
  const factory FnCall.elementGetText(FnCallElementGetText field0) =
      FnCall_ElementGetText;
  const factory FnCall.elementType(FnCallElementType field0) =
      FnCall_ElementType;
  const factory FnCall.elementClick(FnCallElementClick field0) =
      FnCall_ElementClick;
  const factory FnCall.csvNew(FnCallCsvNew field0) = FnCall_CsvNew;
  const factory FnCall.csvLoad(FnCallCsvLoad field0) = FnCall_CsvLoad;
  const factory FnCall.csvSave(FnCallCsvSave field0) = FnCall_CsvSave;
  const factory FnCall.csvGet(FnCallCsvGet field0) = FnCall_CsvGet;
  const factory FnCall.csvSet(FnCallCsvSet field0) = FnCall_CsvSet;
  const factory FnCall.csvRowCount(FnCallCsvRowCount field0) =
      FnCall_CsvRowCount;

  FnCall applyArgs({required Map<String, Val> args}) => RustLib.instance.api
      .crateVplFunctionsFnCallApplyArgs(that: this, args: args);

  List<String> args() =>
      RustLib.instance.api.crateVplFunctionsFnCallFrbOverrideArgs(that: this);

  FnName name() => RustLib.instance.api.crateVplFunctionsFnCallName(that: this);

  Map<String, Val> toArgs() =>
      RustLib.instance.api.crateVplFunctionsFnCallToArgs(that: this);
}

enum FnName {
  systemStop,
  systemPrint,
  systemSleep,
  pageNew,
  pageGetByIndex,
  pageGetCount,
  pageWaitForNavigation,
  pageClose,
  pageFindElement,
  elementGetOuterHtml,
  elementGetInnerHtml,
  elementGetText,
  elementType,
  elementClick,
  csvNew,
  csvLoad,
  csvSave,
  csvGet,
  csvSet,
  csvRowCount;

  List<String> args() =>
      RustLib.instance.api.crateVplFunctionsFnNameFrbOverrideArgs(that: this);

  String display() => RustLib.instance.api
      .crateVplFunctionsFnNameFrbOverrideDisplay(that: this);

  FnCall toCall() =>
      RustLib.instance.api.crateVplFunctionsFnNameToCall(that: this);
}
