// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../shared/abort_controller.dart';
import 'functions.dart';
import 'functions/csv.dart';
import 'functions/element.dart';
import 'functions/page.dart';
import 'functions/system.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'tokens.dart';

// These functions are ignored because they have generic arguments: `unwrap_pointer`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `get_pointer`, `get_variable`, `remove_pointer`, `remove_variable`, `store_pointer`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Interpreter>>
abstract class Interpreter implements RustOpaqueInterface {
  Val evaluateVariable({required Val value});

  Future<void> run({required Scope scope, required AbortController abort});

  factory Interpreter() =>
      RustLib.instance.api.crateVplInterpreterInterpreterNew();

  Val storeVariable({required Identifier ident, required Val value});
}
