// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'functions.dart';
import 'functions/csv.dart';
import 'functions/element.dart';
import 'functions/page.dart';
import 'functions/system.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'tokens.dart';
part 'raw_tokens.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`

class RawFor {
  Val condition;

  RawFor({required this.condition});

  RawFor copy() => RustLib.instance.api.crateVplRawTokensRawForCopy(that: this);

  @override
  int get hashCode => condition.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RawFor &&
          runtimeType == other.runtimeType &&
          condition == other.condition;
}

class RawIf {
  Val condition;

  RawIf({required this.condition});

  RawIf copy() => RustLib.instance.api.crateVplRawTokensRawIfCopy(that: this);

  @override
  int get hashCode => condition.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RawIf &&
          runtimeType == other.runtimeType &&
          condition == other.condition;
}

class RawScope {
  List<RawStatement> field0;

  RawScope({required this.field0});

  RawScope copy() =>
      RustLib.instance.api.crateVplRawTokensRawScopeCopy(that: this);

  Future<Scope> build() => RustLib.instance.api
      .crateVplRawTokensRawScopeFrbOverrideBuild(that: this);

  static RawScope fromBinary({required List<int> binary}) =>
      RustLib.instance.api.crateVplRawTokensRawScopeFromBinary(binary: binary);

  static RawScope fromJson({required String json}) =>
      RustLib.instance.api.crateVplRawTokensRawScopeFromJson(json: json);

  static Future<RawScope?> initial({required String path}) =>
      RustLib.instance.api.crateVplRawTokensRawScopeInitial(path: path);

  static Future<RawScope?> open() =>
      RustLib.instance.api.crateVplRawTokensRawScopeOpen();

  Future<void> save() =>
      RustLib.instance.api.crateVplRawTokensRawScopeSave(that: this);

  Uint8List toBinary() =>
      RustLib.instance.api.crateVplRawTokensRawScopeToBinary(that: this);

  String toJson() =>
      RustLib.instance.api.crateVplRawTokensRawScopeToJson(that: this);

  @override
  int get hashCode => field0.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RawScope &&
          runtimeType == other.runtimeType &&
          field0 == other.field0;
}

@freezed
sealed class RawStatement with _$RawStatement {
  const RawStatement._();

  const factory RawStatement.end() = RawStatement_End;
  const factory RawStatement.if_(RawIf field0) = RawStatement_If;
  const factory RawStatement.for_(RawFor field0) = RawStatement_For;
  const factory RawStatement.call(StatementCall field0) = RawStatement_Call;
  const factory RawStatement.variable(StatementVariable field0) =
      RawStatement_Variable;

  RawStatement copy() =>
      RustLib.instance.api.crateVplRawTokensRawStatementCopy(that: this);

  Future<RawStatementVariant> variant() =>
      RustLib.instance.api.crateVplRawTokensRawStatementVariant(that: this);
}

@freezed
sealed class RawStatementVariant with _$RawStatementVariant {
  const RawStatementVariant._();

  const factory RawStatementVariant.end() = RawStatementVariant_End;
  const factory RawStatementVariant.if_() = RawStatementVariant_If;
  const factory RawStatementVariant.for_() = RawStatementVariant_For;
  const factory RawStatementVariant.variable() = RawStatementVariant_Variable;
  const factory RawStatementVariant.call(FnName field0) =
      RawStatementVariant_Call;

  RawStatementVariant copy() =>
      RustLib.instance.api.crateVplRawTokensRawStatementVariantCopy(that: this);
}
