// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'functions.dart';
import 'functions/csv.dart';
import 'functions/element.dart';
import 'functions/page.dart';
import 'functions/system.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'tokens.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `from`, `from`, `from`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `as_boolean`, `as_computed`, `as_identifier`, `as_number`, `as_object`, `as_string`, `is_boolean`, `is_computed`, `is_identifier`, `is_number`, `is_object`, `is_string`, `unwrap_as_boolean`, `unwrap_as_computed`, `unwrap_as_identifier`, `unwrap_as_number`, `unwrap_as_object`, `unwrap_as_string`

class Identifier {
  String field0;

  Identifier({required this.field0});

  Identifier copy() =>
      RustLib.instance.api.crateVplTokensIdentifierCopy(that: this);

  @override
  int get hashCode => field0.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Identifier &&
          runtimeType == other.runtimeType &&
          field0 == other.field0;
}

class Scope {
  List<Statement> field0;

  Scope({required this.field0});

  Scope copy() => RustLib.instance.api.crateVplTokensScopeCopy(that: this);

  @override
  int get hashCode => field0.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Scope &&
          runtimeType == other.runtimeType &&
          field0 == other.field0;
}

@freezed
sealed class Statement with _$Statement {
  const Statement._();

  const factory Statement.if_(StatementIf field0) = Statement_If;
  const factory Statement.for_(StatementFor field0) = Statement_For;
  const factory Statement.call(StatementCall field0) = Statement_Call;
  const factory Statement.variable(StatementVariable field0) =
      Statement_Variable;

  Statement copy() =>
      RustLib.instance.api.crateVplTokensStatementCopy(that: this);
}

class StatementCall {
  FnCall field0;

  StatementCall({required this.field0});

  StatementCall copy() =>
      RustLib.instance.api.crateVplTokensStatementCallCopy(that: this);

  @override
  int get hashCode => field0.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StatementCall &&
          runtimeType == other.runtimeType &&
          field0 == other.field0;
}

class StatementFor {
  Val condition;
  Scope scope;

  StatementFor({required this.condition, required this.scope});

  StatementFor copy() =>
      RustLib.instance.api.crateVplTokensStatementForCopy(that: this);

  @override
  int get hashCode => condition.hashCode ^ scope.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StatementFor &&
          runtimeType == other.runtimeType &&
          condition == other.condition &&
          scope == other.scope;
}

class StatementIf {
  Val condition;
  Scope scope;

  StatementIf({required this.condition, required this.scope});

  StatementIf copy() =>
      RustLib.instance.api.crateVplTokensStatementIfCopy(that: this);

  @override
  int get hashCode => condition.hashCode ^ scope.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StatementIf &&
          runtimeType == other.runtimeType &&
          condition == other.condition &&
          scope == other.scope;
}

class StatementVariable {
  Identifier ident;
  Val value;

  StatementVariable({required this.ident, required this.value});

  StatementVariable copy() =>
      RustLib.instance.api.crateVplTokensStatementVariableCopy(that: this);

  @override
  int get hashCode => ident.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StatementVariable &&
          runtimeType == other.runtimeType &&
          ident == other.ident &&
          value == other.value;
}

@freezed
sealed class Val with _$Val {
  const Val._();

  const factory Val.null_() = Val_Null;
  const factory Val.identifier(Identifier field0) = Val_Identifier;
  const factory Val.string(ValueString field0) = Val_String;
  const factory Val.number(ValueNumber field0) = Val_Number;
  const factory Val.boolean(ValueBoolean field0) = Val_Boolean;
  const factory Val.object(ValueObject field0) = Val_Object;
  const factory Val.computed(ValueComputed field0) = Val_Computed;

  Future<bool> boolean() =>
      RustLib.instance.api.crateVplTokensValBoolean(that: this);

  Val copy() => RustLib.instance.api.crateVplTokensValCopy(that: this);

  static Future<Val> default_() =>
      RustLib.instance.api.crateVplTokensValDefault();

  Future<String> display() =>
      RustLib.instance.api.crateVplTokensValDisplay(that: this);
}

class ValueBoolean {
  bool field0;

  ValueBoolean({required this.field0});

  ValueBoolean copy() =>
      RustLib.instance.api.crateVplTokensValueBooleanCopy(that: this);

  @override
  int get hashCode => field0.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ValueBoolean &&
          runtimeType == other.runtimeType &&
          field0 == other.field0;
}

class ValueComputed {
  ValueComputedOperation operation;
  Val left;
  Val right;

  ValueComputed({
    required this.operation,
    required this.left,
    required this.right,
  });

  ValueComputed copy() =>
      RustLib.instance.api.crateVplTokensValueComputedCopy(that: this);

  @override
  int get hashCode => operation.hashCode ^ left.hashCode ^ right.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ValueComputed &&
          runtimeType == other.runtimeType &&
          operation == other.operation &&
          left == other.left &&
          right == other.right;
}

enum ValueComputedOperation {
  add,
  subtract,
  multiply,
  divide,
  modulo,
  boolAnd,
  boolOr,
  boolEqual,
  boolNotEqual,
  boolLessThan,
  boolLessThanOrEqual,
  boolGreaterThan,
  boolGreatherThanOrEqual;

  ValueComputedOperation copy() =>
      RustLib.instance.api.crateVplTokensValueComputedOperationCopy(that: this);
}

class ValueNumber {
  double field0;

  ValueNumber({required this.field0});

  ValueNumber copy() =>
      RustLib.instance.api.crateVplTokensValueNumberCopy(that: this);

  @override
  int get hashCode => field0.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ValueNumber &&
          runtimeType == other.runtimeType &&
          field0 == other.field0;
}

class ValueObject {
  final String symbol;

  const ValueObject({required this.symbol});

  ValueObject copy() =>
      RustLib.instance.api.crateVplTokensValueObjectCopy(that: this);

  @override
  int get hashCode => symbol.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ValueObject &&
          runtimeType == other.runtimeType &&
          symbol == other.symbol;
}

class ValueString {
  String field0;

  ValueString({required this.field0});

  ValueString copy() =>
      RustLib.instance.api.crateVplTokensValueStringCopy(that: this);

  @override
  int get hashCode => field0.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ValueString &&
          runtimeType == other.runtimeType &&
          field0 == other.field0;
}
