// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

class AiSettings {
  final String textUrl;
  final String textKey;
  final String textModel;
  final String embedUrl;
  final String embedKey;
  final String embedModel;
  final int embedDimensions;

  const AiSettings({
    required this.textUrl,
    required this.textKey,
    required this.textModel,
    required this.embedUrl,
    required this.embedKey,
    required this.embedModel,
    required this.embedDimensions,
  });

  static Future<AiSettings> current() =>
      RustLib.instance.api.crateAiSettingsAiSettingsCurrent();

  static Future<AiSettings> empty() =>
      RustLib.instance.api.crateAiSettingsAiSettingsEmpty();

  Future<void> update() =>
      RustLib.instance.api.crateAiSettingsAiSettingsUpdate(that: this);

  @override
  int get hashCode =>
      textUrl.hashCode ^
      textKey.hashCode ^
      textModel.hashCode ^
      embedUrl.hashCode ^
      embedKey.hashCode ^
      embedModel.hashCode ^
      embedDimensions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiSettings &&
          runtimeType == other.runtimeType &&
          textUrl == other.textUrl &&
          textKey == other.textKey &&
          textModel == other.textModel &&
          embedUrl == other.embedUrl &&
          embedKey == other.embedKey &&
          embedModel == other.embedModel &&
          embedDimensions == other.embedDimensions;
}
