// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'singleton.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `initialize_client`, `initialize_mcp`, `initialize`, `map_tool`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AiSingletonInner`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AiSingleton>>
abstract class AiSingleton implements RustOpaqueInterface {
  AiSingleton copy();

  static Future<AiSingleton> instance() =>
      RustLib.instance.api.crateAiSingletonAiSingletonFrbOverrideInstance();

  Future<void> prompt({
    required String prompt,
    required List<AiHistory> history,
    required FutureOr<void> Function(AiResponse) cb,
  });
}

@freezed
sealed class AiHistory with _$AiHistory {
  const AiHistory._();

  const factory AiHistory.assistant(String field0) = AiHistory_Assistant;
  const factory AiHistory.user(String field0) = AiHistory_User;
}

@freezed
sealed class AiResponse with _$AiResponse {
  const AiResponse._();

  const factory AiResponse.tool(String field0) = AiResponse_Tool;
  const factory AiResponse.response(String field0) = AiResponse_Response;
}
