name: Build Windows

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64

      - name: Install flutter_rust_bridge_codegen
        run: cargo install flutter_rust_bridge_codegen --version 2.12.0

      - name: Generate FRB binding
        run: flutter_rust_bridge_codegen generate

      - name: Get dependencies
        run: flutter pub get

      - name: Build Windows app
        run: flutter build windows --release

      - name: Tar build output
        run: |
          cd build/windows/x64/runner
          tar -czf ../../../../ikarus-windows-x64.tar.gz Release

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ikarus-windows-x64
          archive: false
          path: ikarus-windows-x64.tar.gz
